### ISSUE TITLE
org export with the old engine (< 8.0.0)

### ISSUE THREAD

**Issue by cerkut** [yoshinari-nomura/orglue#8]
orglue-evernote-create-note-from-org-buffer () seems to use the old export engine, would it be possible to check the org-version and if it is bigger than 8.0.0 use the new export commands, e.g., 

(org-infile-export-plist) -> (org-export-get-environment)

etc?

**Comment by yoshinari-nomura** [comment]
Thanks,

I've noticed that ``orglue-evernote-create-note-from-org-buffe``  in my local repository was already changed not to use old org stuffs.

I'll take a time to tidy up the code and push to public. Please wait a little.

**Comment by yoshinari-nomura** [comment]
Hi @cerkut, 

I've written the more powerful function than  ``orglue-evernote-create-note-from-org-buffe``
as ``epic-create-note-from-org-buffer`` in epic package.
Please drop in https://github.com/yoshinari-nomura/epic/

Also, I put these code in orglue.el,
You can still use  ``orglue-evernote-create-note-from-org-buffe``
```
(defalias 'orglue-evernote-create-note-from-org-buffer
  'epic-create-note-from-org-buffer)
```

**Comment by cerkut** [comment]
Thank you, I’ve noticed the change at melpa epic package; works quite nicely.

**Comment by yoshinari-nomura** [comment]
OK, let me close this issue then.
